#! /usr/bin/env bash

GENERATOR="MinGW Makefiles"

mkdir modules/glad/build
cd modules/glad/build
cmake .. -G "$GENERATOR"
make

cp -R include/* ../../../sources
cp src/glad.c ../../../sources/glad/glad.c

cd ../../../

mkdir -p build
cd build
cmake .. -G "$GENERATOR"
