#! /usr/bin/env bash

GENERATOR="Unix Makefiles"

mkdir modules/glad/build
cd modules/glad/build
cmake .. -G "$GENERATOR"
make

cp -R include/* ../../../src
cp src/glad.c ../../../src/glad/glad.c

cd ../../../

mkdir modules/opencv/build
cd modules/opencv/build
cmake .. -G "$GENERATOR"
make
make install

cd ../../../

mkdir -p build
cd build
cmake .. -G "$GENERATOR"
